/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms;

import java.time.LocalTime;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author hp
 */
public class page1 extends javax.swing.JFrame {

    /**
     * Creates new form page1
     */
    public page1() {
        initComponents();
                pub_date.setMinSelectableDate(new java.util.Date());
                del.setVisible(false);
                delcode.setVisible(false);
                deltrain.setVisible(false);
                back.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        deltrain = new javax.swing.JButton();
        delcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ticket_price = new javax.swing.JTextField();
        total_stops = new javax.swing.JTextField();
        total_time = new javax.swing.JTextField();
        arrival = new javax.swing.JTextField();
        departure = new javax.swing.JTextField();
        tos = new javax.swing.JTextField();
        froms = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_code = new javax.swing.JTextField();
        publish = new javax.swing.JButton();
        pub_date = new com.toedter.calendar.JDateChooser();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        search = new javax.swing.JButton();
        back = new javax.swing.JButton();
        del = new javax.swing.JButton();
        mainlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deltrain.setBackground(new java.awt.Color(0, 255, 255));
        deltrain.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        deltrain.setForeground(new java.awt.Color(255, 255, 255));
        deltrain.setText("DELETE");
        deltrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltrainActionPerformed(evt);
            }
        });
        panel.add(deltrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, -1, -1));

        delcode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delcode.setText("ENTER TRAIN CODE");
        delcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delcodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delcodeMouseEntered(evt);
            }
        });
        panel.add(delcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 290, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RAILWAY  MANAGEMENT SYSTEM");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        ticket_price.setText("TICKET PRICE");
        ticket_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket_priceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ticket_priceMouseEntered(evt);
            }
        });
        ticket_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_priceActionPerformed(evt);
            }
        });
        panel.add(ticket_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 410, 60));

        total_stops.setText("TOTAL STOPS");
        total_stops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_stopsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                total_stopsMouseEntered(evt);
            }
        });
        panel.add(total_stops, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 410, 60));

        total_time.setText("TOTAL TIME ");
        total_time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_timeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                total_timeMouseEntered(evt);
            }
        });
        panel.add(total_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 410, 60));

        arrival.setText("ARRIVAL");
        arrival.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrivalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrivalMouseEntered(evt);
            }
        });
        panel.add(arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 410, 60));

        departure.setText("DEPARTURE");
        departure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                departureMouseEntered(evt);
            }
        });
        panel.add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 410, 60));

        tos.setText("TO");
        tos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tosMouseEntered(evt);
            }
        });
        panel.add(tos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 410, 60));

        froms.setText("FROM");
        froms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fromsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fromsMouseEntered(evt);
            }
        });
        panel.add(froms, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 410, 60));

        t_name.setText("TRAIN NAME");
        t_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_nameMouseEntered(evt);
            }
        });
        panel.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 410, 60));

        t_code.setText("TRAIN CODE");
        t_code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_codeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_codeMouseEntered(evt);
            }
        });
        panel.add(t_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 410, 60));

        publish.setBackground(new java.awt.Color(102, 51, 0));
        publish.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        publish.setForeground(new java.awt.Color(255, 255, 255));
        publish.setText("PUBLISH");
        publish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishActionPerformed(evt);
            }
        });
        panel.add(publish, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 300, 70));
        panel.add(pub_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 410, 60));

        update.setBackground(new java.awt.Color(0, 255, 255));
        update.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE TRAIN INFORMATION");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        panel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 480, 70));

        delete.setBackground(new java.awt.Color(0, 255, 255));
        delete.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE TRAIN");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        panel.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 480, -1));

        view.setBackground(new java.awt.Color(0, 255, 255));
        view.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("VIEW ALL TRAINS");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        panel.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 480, -1));

        exit.setBackground(new java.awt.Color(102, 51, 0));
        exit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, -1, -1));

        search.setBackground(new java.awt.Color(0, 255, 255));
        search.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH TRAIN");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        panel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 480, -1));

        back.setBackground(new java.awt.Color(0, 255, 255));
        back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        panel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, -1, -1));

        del.setBackground(new java.awt.Color(102, 51, 0));
        del.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 670, 350));

        mainlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/railpic.jpg"))); // NOI18N
        panel.add(mainlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1370, 770));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticket_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket_priceMouseClicked
        // TODO add your handling code here:
                      ticket_price.setText("");

    }//GEN-LAST:event_ticket_priceMouseClicked

    private void ticket_priceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket_priceMouseEntered
        // TODO add your handling code here:
         if(ticket_price.getText().trim().isEmpty()){
          ticket_price.setText("TICKET PRICE");
    } 
    }//GEN-LAST:event_ticket_priceMouseEntered

    private void total_stopsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_stopsMouseClicked
        // TODO add your handling code here:
                        total_stops.setText("");

    }//GEN-LAST:event_total_stopsMouseClicked

    private void total_stopsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_stopsMouseEntered
        // TODO add your handling code here:
         if(total_stops.getText().trim().isEmpty()){
          total_stops.setText("TOTAL STOPS");
    } 
    }//GEN-LAST:event_total_stopsMouseEntered

    private void total_timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_timeMouseClicked
        // TODO add your handling code here:
              total_time.setText("");

    }//GEN-LAST:event_total_timeMouseClicked

    private void total_timeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_timeMouseEntered
        // TODO add your handling code here:
        if(total_time.getText().trim().isEmpty()){
          total_time.setText("TOTAL TIME");
    }     
    }//GEN-LAST:event_total_timeMouseEntered

    private void arrivalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrivalMouseClicked
        // TODO add your handling code here:
                                  arrival.setText("");

    }//GEN-LAST:event_arrivalMouseClicked

    private void arrivalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrivalMouseEntered
        // TODO add your handling code here:
         if(arrival.getText().trim().isEmpty()){
          arrival.setText("ARRIVAL");
    }//GEN-LAST:event_arrivalMouseEntered
    }
    private void departureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departureMouseClicked
        // TODO add your handling code here:
                           departure.setText("");

    }//GEN-LAST:event_departureMouseClicked

    private void departureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departureMouseEntered
        // TODO add your handling code here:
          if(departure.getText().trim().isEmpty()){
          departure.setText("DEPARTURE");
    }//GEN-LAST:event_departureMouseEntered
    }
    private void tosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tosMouseClicked
        // TODO add your handling code here:
                   tos.setText("");

    }//GEN-LAST:event_tosMouseClicked

    private void tosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tosMouseEntered
        // TODO add your handling code here:
          if(tos.getText().trim().isEmpty()){
          tos.setText("TO");
    }
    }//GEN-LAST:event_tosMouseEntered

    private void fromsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromsMouseClicked
        // TODO add your handling code here:
           froms.setText("");

    }//GEN-LAST:event_fromsMouseClicked

    private void fromsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromsMouseEntered
        // TODO add your handling code here:
         if(froms.getText().trim().isEmpty()){
            froms.setText("FROM");
    }        
    }//GEN-LAST:event_fromsMouseEntered

    private void t_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_nameMouseClicked
        // TODO add your handling code here:
                        t_name.setText("");

    }//GEN-LAST:event_t_nameMouseClicked

    private void t_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_nameMouseEntered
        // TODO add your handling code here:
           if(t_name.getText().trim().isEmpty()){
            t_name.setText("TRAIN NAME");
    }//GEN-LAST:event_t_nameMouseEntered
    }
    private void t_codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_codeMouseClicked
        // TODO add your handling code here:
                t_code.setText("");

    }//GEN-LAST:event_t_codeMouseClicked

    private void t_codeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_codeMouseEntered
        // TODO add your handling code here:
         if(t_code.getText().trim().isEmpty()){
            t_code.setText("TRAIN CODE");
        }
    }//GEN-LAST:event_t_codeMouseEntered

    private void ticket_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticket_priceActionPerformed

    private void publishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishActionPerformed
        // TODO add your handling code here:
            Dbms go = new Dbms();
    String code= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,30}";
    Pattern p=Pattern.compile(code);
    Matcher m=p.matcher(t_code.getText());
    Boolean match=m.find();
    
    String trainname= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,100}";
    Pattern p2=Pattern.compile(trainname);
    Matcher m2=p2.matcher(t_name.getText());
    Boolean match2=m2.find();
    
    String from= "[A-Za-z0-9]{1,50}";
    Pattern p3=Pattern.compile(from);
    Matcher m3=p3.matcher(froms.getText());
    Boolean match3=m3.find();
    
    String to= "[A-Za-z0-9]{1,50}";
    Pattern p4=Pattern.compile(to);
    Matcher m4=p4.matcher(tos.getText());
    Boolean match4=m4.find();
    
    String d_time= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,100}";
    Pattern p5=Pattern.compile(d_time);
    Matcher m5=p5.matcher(departure.getText());
    Boolean match5=m5.find();
   
   String a_time= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,100}";
    Pattern p6=Pattern.compile(a_time);
    Matcher m6=p6.matcher(arrival.getText());
    Boolean match6=m6.find();
   
     String t_time= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,100}";
    Pattern p7=Pattern.compile(t_time);
    Matcher m7=p7.matcher(total_time.getText());
    Boolean match7=m7.find();
    
    String t_stops= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,100}";
    Pattern p8=Pattern.compile(t_stops);
    Matcher m8=p8.matcher(total_stops.getText());
    Boolean match8=m8.find();
    
      String t_price= "[0-9]{1,100}";
    Pattern p9=Pattern.compile(t_price);
    Matcher m9=p9.matcher(ticket_price.getText());
    Boolean match9=m9.find();
   
        LocalTime currentTime = LocalTime.now();
        
     if(t_code.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER TRAIN CODE", "PUBLISH",2);

     }   
     else if(t_name.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER TRAIN NAME", "PUBLISH",2);

     }   
      else if(froms.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER FROM STATION", "PUBLISH",2);

     }
      else if(tos.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER TO STATION", "PUBLISH",2);

     }
      else if(departure.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER DEPARTURE TIME", "PUBLISH",2);

     }
      else if(arrival.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER ARRIVAL TIME", "PUBLISH",2);

     }
      else if(total_time.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER TOTAL TIME TAKEN TO ARRIVE AT THE DESTINATION", "PUBLISH",2);

     }
      else if(total_stops.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER TOTAL STOPS", "PUBLISH",2);

     }
      else if(ticket_price.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "ENTER TICKET PRICE", "PUBLISH",2);

     }
      else if(pub_date.getCalendar()==null){
        JOptionPane.showMessageDialog(this, "ENTER TRAIN'S PUBLISH DATE", "PUBLISH",2);

     }
     else if(!match)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Train Code OR Use Unique Train Code ", "SIGN UP",2);
 
   }
   else if(!match2)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Train Name ", "SIGN UP",2);
 
   }else if(!match3)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct From Station ", "SIGN UP",2);
 
   }else if(!match4)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct To Station", "SIGN UP",2);
 
   }
   else if(!match5)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Departure Time ", "SIGN UP",2);
 
   }
  
   else if(!match6)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Arrival Time ", "SIGN UP",2);
 
   }
     else if(!match7)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Total Time ", "SIGN UP",2);
 
   }
       else if(!match8)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Total Stops", "SIGN UP",2);
 
   }
         else if(!match9 )
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Ticket Price ", "SIGN UP",2);
 
   }
   
   else
  {
       if(go.train_info(t_code.getText(), t_name.getText(), froms.getText(), tos.getText(), departure.getText(), arrival.getText(), total_time.getText(),total_stops.getText(), Integer.parseInt(ticket_price.getText()),currentTime.toString(),((JTextField) pub_date.getDateEditor().getUiComponent()).getText())==1)
   {
        
        JOptionPane.showMessageDialog(this, "TRAIN PUBLISHED", "SIGN UP",1);
       
        
   }
       else{
                            JOptionPane.showMessageDialog(this, "ENTER UNIQUE TRAIN CODE", "SIGN UP",2);
       }
  }
    
    }//GEN-LAST:event_publishActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        del.setVisible(true);
        delcode.setVisible(true);
        deltrain.setVisible(true);
        back.setVisible(true);
        delete.setVisible(false);
                view.setVisible(false);
        search.setVisible(false);
        update.setVisible(false);
        t_name.setEditable(false);
        t_code.setEditable(false);
        froms.setEditable(false);
        tos.setEditable(false);
        departure.setEditable(false);
        arrival.setEditable(false);
        total_time.setEditable(false);
        total_stops.setEditable(false);
        ticket_price.setEditable(false);
        pub_date.setVisible(false);
        publish.setVisible(false);
        exit.setVisible(false);


        
        

        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        view go=new view();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search go= new search();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
           del.setVisible(false);
        delcode.setVisible(false);
        deltrain.setVisible(false);
        back.setVisible(false);
        delete.setVisible(true);
                view.setVisible(true);
        search.setVisible(true);
        update.setVisible(true);
        t_name.setEditable(true);
        t_code.setEditable(true);
        froms.setEditable(true);
        tos.setEditable(true);
        departure.setEditable(true);
        arrival.setEditable(true);
        total_time.setEditable(true);
        total_stops.setEditable(true);
        ticket_price.setEditable(true);
        pub_date.setVisible(true);
        publish.setVisible(true);
        exit.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void deltrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltrainActionPerformed
        // TODO add your handling code here:
        Dbms go=new Dbms();
        if(go.deletetrain(delcode.getText())==1)
        {
             
            JOptionPane.showMessageDialog(this, "TRAIN RECORD DELETED","alert",1);
        }
        else
        {
                        JOptionPane.showMessageDialog(this, "TRAIN NOT FOUND","alert",2);

        }
        
        
        
    }//GEN-LAST:event_deltrainActionPerformed

    private void delcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delcodeMouseClicked
        // TODO add your handling code here:
                        delcode.setText("");

    }//GEN-LAST:event_delcodeMouseClicked

    private void delcodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delcodeMouseEntered
        // TODO add your handling code here:
        if(delcode.getText().trim().isEmpty()){
           delcode.setText("ENTER TRAIN CODE");
        }
    }//GEN-LAST:event_delcodeMouseEntered

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        updatetrain go=new updatetrain();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrival;
    private javax.swing.JButton back;
    private javax.swing.JButton del;
    private javax.swing.JTextField delcode;
    private javax.swing.JButton delete;
    private javax.swing.JButton deltrain;
    private javax.swing.JTextField departure;
    private javax.swing.JButton exit;
    private javax.swing.JTextField froms;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JPanel panel;
    private com.toedter.calendar.JDateChooser pub_date;
    private javax.swing.JButton publish;
    private javax.swing.JButton search;
    private javax.swing.JTextField t_code;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField ticket_price;
    private javax.swing.JTextField tos;
    private javax.swing.JTextField total_stops;
    private javax.swing.JTextField total_time;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
