/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import javax.swing.JOptionPane;

/**
 *
 * @author kk
 */
public class updatetrain extends javax.swing.JFrame {

    /**
     * Creates new form updatetrain
     */
    public updatetrain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        traincode = new javax.swing.JTextField();
        updaterecord = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RAILWAY  MANAGEMENT SYSTEM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 51, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, -1, 50));

        traincode.setText("ENTER TRAIN CODE");
        traincode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traincodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                traincodeMouseEntered(evt);
            }
        });
        traincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traincodeActionPerformed(evt);
            }
        });
        jPanel1.add(traincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 300, 50));

        updaterecord.setText("ENTER NEW RECORD");
        updaterecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updaterecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updaterecordMouseEntered(evt);
            }
        });
        jPanel1.add(updaterecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 300, 50));

        update.setBackground(new java.awt.Color(102, 51, 0));
        update.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 210, 50));

        field.setText("ENTER THE FIELD NAME TO UPDATE ITS RECORD");
        field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fieldMouseEntered(evt);
            }
        });
        jPanel1.add(field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 300, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/railpic.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        page1 go=new page1();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void traincodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traincodeMouseClicked
        // TODO add your handling code here:
        traincode.setText("");
    }//GEN-LAST:event_traincodeMouseClicked

    private void traincodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traincodeMouseEntered
        // TODO add your handling code here:
        if(traincode.getText().trim().isEmpty()){
            traincode.setText("ENTER TRAIN CODE");
        }
    }//GEN-LAST:event_traincodeMouseEntered

    private void traincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traincodeActionPerformed

    private void updaterecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updaterecordMouseClicked
        // TODO add your handling code here:
        updaterecord.setText("");
    }//GEN-LAST:event_updaterecordMouseClicked

    private void updaterecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updaterecordMouseEntered
        // TODO add your handling code here:
        if(updaterecord.getText().trim().isEmpty()){
            updaterecord.setText("ENTER NEW RECORD");
        }
    }//GEN-LAST:event_updaterecordMouseEntered

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
          Dbms go= new Dbms();
      
        if(traincode.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ENTER TRAIN CODE", "UPDATE RECORD",2);
                
            }
           
             else if(field.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ENTER FIELD NAME", "UPDATE RECORD",2);
                
            }
             
               else if(updaterecord.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "ENTER NEW REOCRD", "UPDATE RECORD",2);
                
            }
         
           else 
            {
               
               if(go.updatetrain(traincode.getText(), field.getText(), updaterecord.getText())==1)
                {
                JOptionPane.showMessageDialog(this, "RECORD HAS BEEN UPDATED", "UPDATE RECORD",1);
                }
                else
                {
                                    JOptionPane.showMessageDialog(this, "NO RECORD FOUND", "UPDATE RECORD",2);

                }
            }

     
        
    }//GEN-LAST:event_updateActionPerformed

    private void fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldMouseClicked
        // TODO add your handling code here:
                field.setText("");

    }//GEN-LAST:event_fieldMouseClicked

    private void fieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldMouseEntered
        // TODO add your handling code here:
        if(field.getText().trim().isEmpty()){
            field.setText("ENTER THE FIELD NAME TO UPDATE ITS RECORD");
        }
    }//GEN-LAST:event_fieldMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatetrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatetrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatetrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatetrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatetrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField traincode;
    private javax.swing.JButton update;
    private javax.swing.JTextField updaterecord;
    // End of variables declaration//GEN-END:variables
}
